name: CI
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  x86_64-gnu-aux:
    name: x86_64-gnu-aux
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      CI_JOB_NAME: x86_64-gnu-aux
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      HEAD_SHA: ${{ github.sha }}
      DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SCCACHE_DISABLE: "1"
      CARGO_BUILD_JOBS: "32"
      CMAKE_BUILD_PARALLEL_LEVEL: "32"
      MAKEFLAGS: "-j32"
      NINJAFLAGS: "-j32"
      MAX_JOBS: "32"
      RUST_BACKTRACE: "1"

    steps:
      - name: show runner info
        run: |
          echo "nproc=$(nproc)"
          uname -a
          df -h
      - name: disable git crlf conversion
        run: git config --global core.autocrlf false

      - name: checkout the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: free up disk space
        continue-on-error: true
        run: src/ci/scripts/free-disk-space-linux.sh

      - name: add extra environment variables
        continue-on-error: true
        run: src/ci/scripts/setup-environment.sh
        env:
          EXTRA_VARIABLES: "{}"

      - name: collect CPU statistics
        continue-on-error: true
        run: src/ci/scripts/collect-cpu-stats.sh

      - name: install sccache
        continue-on-error: true
        run: src/ci/scripts/install-sccache.sh

      - name: install clang
        continue-on-error: true
        run: src/ci/scripts/install-clang.sh

      - name: checkout submodules
        run: src/ci/scripts/checkout-submodules.sh

      - name: install ninja
        continue-on-error: true
        run: src/ci/scripts/install-ninja.sh

      - name: enable ipv6 on Docker
        continue-on-error: true
        run: src/ci/scripts/enable-docker-ipv6.sh

      - name: setup rust
        run: |
          if command -v cargo &>/dev/null; then
            echo "Cargo found in PATH"
          elif [ -f "$HOME/.cargo/env" ]; then
            source "$HOME/.cargo/env"
            echo "PATH=$PATH" >> "$GITHUB_ENV"
          else
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
            echo "PATH=$HOME/.cargo/bin:$PATH" >> "$GITHUB_ENV"
          fi
          rustc --version
          cargo --version
      - name: build citool
        run: |
          cd src/ci/citool
          CARGO_INCREMENTAL=0 CARGO_TARGET_DIR=../../../build/citool cargo build
      - name: run the build
        run: |
          set +e
          src/ci/scripts/run-build-from-ci.sh 2>&1
          STATUS=$?
          set -e
          exit ${STATUS}
      - name: print final disk usage
        if: always()
        run: df -h

      - name: upload artifacts to github
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rust-x86_64-gnu-aux-artifacts
          path: obj/artifacts/doc
          if-no-files-found: ignore
          retention-days: 5
